export const categories = [
  { id: "moisturizers", name: "Moisturizers", description: "Hydrate and nourish all day", icon: "💧" },
  { id: "serums", name: "Serums & Treatments", description: "Targeted solutions for every concern", icon: "✨" },
  { id: "cleansers", name: "Cleansers & Toners", description: "Start fresh with every wash", icon: "🧼" },
  { id: "masks", name: "Masks", description: "Weekly treatments for visible results", icon: "🎭" },
  { id: "sun-care", name: "Sun Care", description: "Protection that feels like nothing", icon: "☀️" },
  { id: "tools", name: "Tools & Accessories", description: "Elevate your skincare ritual", icon: "🛠️" },
];

export const products = [
  // === Moisturizers ===
  {
    id: 1,
    name: "Hydrating Facial Serum",
    price: 38,
    description: "Lightweight hyaluronic acid serum for deep hydration and plumping.",
    category: "serums",
    image: "serum-bottle",
  },
  {
    id: 2,
    name: "Vitamin C Brightening Cream",
    price: 42,
    description: "Rich vitamin C moisturizer that evens tone and boosts radiance.",
    category: "moisturizers",
    image: "cream-jar",
  },
  {
    id: 9,
    name: "Cloud Dew Moisturizer",
    price: 36,
    description: "Weightless gel-cream with squalane and ceramides for barrier repair.",
    category: "moisturizers",
    image: "moisturizer-jar",
  },
  {
    id: 10,
    name: "Midnight Renewal Night Cream",
    price: 52,
    description: "Rich overnight cream with peptides and bakuchiol for renewal while you sleep.",
    category: "moisturizers",
    image: "night-cream",
  },
  // === Serums & Treatments ===
  {
    id: 3,
    name: "Retinol Night Oil",
    price: 48,
    description: "Overnight retinol treatment for smoother, younger-looking skin.",
    category: "serums",
    image: "oil-dropper",
  },
  {
    id: 12,
    name: "Niacinamide 10% + Zinc",
    price: 30,
    description: "Pore-minimizing, oil-balancing serum for clear, smooth texture.",
    category: "serums",
    image: "serum-bottle",
  },
  {
    id: 13,
    name: "Peptide Eye Lift Serum",
    price: 44,
    description: "Depuffing eye serum with Matrixyl 3000 and caffeine for brighter eyes.",
    category: "serums",
    image: "oil-dropper",
  },
  // === Cleansers & Toners ===
  {
    id: 4,
    name: "Hyaluronic Acid Mist",
    price: 28,
    description: "On-the-go hydrating mist with hyaluronic acid and rose water.",
    category: "cleansers",
    image: "mist-spray",
  },
  {
    id: 14,
    name: "Oil Cleansing Balm",
    price: 32,
    description: "Silky balm that melts away makeup, SPF, and impurities without stripping.",
    category: "cleansers",
    image: "cream-jar",
  },
  {
    id: 15,
    name: "Gentle Foaming Cleanser",
    price: 24,
    description: "Non-stripping foaming wash with green tea and aloe for daily cleansing.",
    category: "cleansers",
    image: "mist-spray",
  },
  // === Masks ===
  {
    id: 8,
    name: "Collagen Boost Mask",
    price: 16,
    description: "Sheet mask infused with collagen peptides for firming and lifting.",
    category: "masks",
    image: "sheet-mask",
  },
  {
    id: 16,
    name: "Purifying Clay Mask",
    price: 26,
    description: "Kaolin clay mask with charcoal and tea tree to draw out impurities.",
    category: "masks",
    image: "cream-jar",
  },
  {
    id: 17,
    name: "Overnight Hydra Mask",
    price: 34,
    description: "Leave-on sleeping mask with hyaluronic acid for next-day glow.",
    category: "masks",
    image: "night-cream",
  },
  // === Sun Care ===
  {
    id: 18,
    name: "Daily Mineral SPF 50",
    price: 38,
    description: "Zinc-based sunscreen with zero white cast. Lightweight and reef-safe.",
    category: "sun-care",
    image: "serum-bottle",
  },
  {
    id: 19,
    name: "Tinted SPF 30 Glow Drops",
    price: 40,
    description: "Sheer tinted sunscreen that evens skin tone while protecting.",
    category: "sun-care",
    image: "oil-dropper",
  },
  // === Tools & Accessories ===
  {
    id: 5,
    name: "Rose Quartz Gua Sha",
    price: 22,
    description: "Hand-carved rose quartz tool for facial massage and lymphatic drainage.",
    category: "tools",
    image: "gua-sha",
  },
  {
    id: 6,
    name: "Silk Sleep Mask",
    price: 18,
    description: "Luxurious mulberry silk sleep mask for beauty rest.",
    category: "tools",
    image: "sleep-mask",
  },
  {
    id: 20,
    name: "Ice Facial Roller",
    price: 20,
    description: "Cryo roller for depuffing, toning, and refreshing tired skin.",
    category: "tools",
    image: "gua-sha",
  },
];

export const treatments = [
  {
    id: "t1",
    name: "Glō Radiance Facial",
    price: 120,
    duration: "60 min",
    description: "Signature facial combining deep cleansing, gentle exfoliation, and a hydrating mask for instant glow.",
    highlights: ["Deep cleanse & exfoliation", "Custom hydrating mask", "Facial massage", "Instant radiance"],
  },
  {
    id: "t2",
    name: "Deep Cleanse Facial",
    price: 95,
    duration: "45 min",
    description: "Targeted treatment for congested skin with extractions, salicylic acid, and purifying mask.",
    highlights: ["Salicylic acid treatment", "Professional extractions", "Purifying clay mask", "Pore refinement"],
  },
  {
    id: "t3",
    name: "HydraGlow Treatment",
    price: 150,
    duration: "75 min",
    description: "Advanced hydration therapy with hyaluronic acid infusion and LED light therapy.",
    highlights: ["HA infusion therapy", "LED light therapy (red/blue)", "Hydrating sheet mask", "Long-lasting dewiness"],
  },
  {
    id: "t4",
    name: "Anti-Aging Lift Facial",
    price: 180,
    duration: "90 min",
    description: "Microcurrent facial lifting with collagen-boosting serums and lymphatic drainage massage.",
    highlights: ["Microcurrent lifting", "Collagen-boosting serums", "Lymphatic drainage", "Visible lift results"],
  },
  {
    id: "t5",
    name: "Acne Rescue Facial",
    price: 110,
    duration: "60 min",
    description: "Soothing treatment for acne-prone skin with antibacterial ingredients and calming mask.",
    highlights: ["Antibacterial steam treatment", "Calming azulene mask", "LED blue light therapy", "Non-irritating extractions"],
  },
];

export const testimonials = [
  {
    id: "rev1",
    name: "Emily R.",
    text: "The HydraGlow treatment changed my skin completely. I've never felt more confident without makeup!",
    rating: 5,
    product: "HydraGlow Treatment",
  },
  {
    id: "rev2",
    name: "Jessica K.",
    text: "Their Vitamin C cream is the only thing that's actually faded my dark spots. Obsessed.",
    rating: 5,
    product: "Vitamin C Brightening Cream",
  },
  {
    id: "rev3",
    name: "Maya T.",
    text: "Finally a spa that understands sensitive skin. No reactions, just results. The team is incredible.",
    rating: 5,
    product: "Glō Radiance Facial",
  },
  {
    id: "rev4",
    name: "Lauren W.",
    text: "The peptide eye serum erased my under-eye circles in two weeks. I'm a customer for life.",
    rating: 5,
    product: "Peptide Eye Lift Serum",
  },
];