export const products = [
  {
    id: 1,
    name: "Hydrating Facial Serum",
    price: 38,
    description: "Lightweight hyaluronic acid serum for deep hydration and plumping.",
    category: "serums",
    image: "💧",
  },
  {
    id: 2,
    name: "Vitamin C Brightening Cream",
    price: 42,
    description: "Rich vitamin C moisturizer that evens tone and boosts radiance.",
    category: "moisturizers",
    image: "🍊",
  },
  {
    id: 3,
    name: "Retinol Night Oil",
    price: 48,
    description: "Overnight retinol treatment for smoother, younger-looking skin.",
    category: "serums",
    image: "🌙",
  },
  {
    id: 4,
    name: "Hyaluronic Acid Mist",
    price: 28,
    description: "On-the-go hydrating mist with hyaluronic acid and rose water.",
    category: "toners",
    image: "🌹",
  },
  {
    id: 5,
    name: "Rose Quartz Gua Sha",
    price: 22,
    description: "Hand-carved rose quartz tool for facial massage and lymphatic drainage.",
    category: "tools",
    image: "🌸",
  },
  {
    id: 6,
    name: "Silk Sleep Mask",
    price: 18,
    description: "Luxurious mulberry silk sleep mask for beauty rest.",
    category: "accessories",
    image: "🛌",
  },
  {
    id: 7,
    name: "CBD Recovery Balm",
    price: 34,
    description: "Calming CBD balm with chamomile for sensitive or irritated skin.",
    category: "moisturizers",
    image: "🌿",
  },
  {
    id: 8,
    name: "Collagen Boost Mask",
    price: 16,
    description: "Sheet mask infused with collagen peptides for firming and lifting.",
    category: "masks",
    image: "✨",
  },
];

export const treatments = [
  {
    id: "t1",
    name: "Glō Radiance Facial",
    price: 120,
    duration: "60 min",
    description: "Signature facial combining deep cleansing, gentle exfoliation, and a hydrating mask for instant glow.",
  },
  {
    id: "t2",
    name: "Deep Cleanse Facial",
    price: 95,
    duration: "45 min",
    description: "Targeted treatment for congested skin with extractions, salicylic acid, and purifying mask.",
  },
  {
    id: "t3",
    name: "HydraGlow Treatment",
    price: 150,
    duration: "75 min",
    description: "Advanced hydration therapy with hyaluronic acid infusion and LED light therapy.",
  },
  {
    id: "t4",
    name: "Anti-Aging Lift Facial",
    price: 180,
    duration: "90 min",
    description: "Microcurrent facial lifting with collagen-boosting serums and lymphatic drainage massage.",
  },
  {
    id: "t5",
    name: "Acne Rescue Facial",
    price: 110,
    duration: "60 min",
    description: "Soothing treatment for acne-prone skin with antibacterial ingredients and calming mask.",
  },
];
